Fix compilation when DEBUG_PATHS is defined
Error message:

modmgr.cc: In constructor 'ModManager::ModManager(const std::string&, const std::string&, bool, bool)':
modmgr.cc:544:86: error: 'src_dir' was not declared in this scope
  544 |                         cout << "setting " << cfgname << " source directory to: " << src_dir
      |                                                                                      ^~~~~~~

Fixing by harmonizing the `src_dir` handling like the other ones.

Signed-off-by: Vincent Legoll <vincent.legoll@gmail.com>